[FIX] l10n_mx_edi_vendor_bills/customer: Avoid recalculate taxes.
When a CFDI has more decimals that Odoo, when you try to re-calculate
the taxes, an error is shown because the amounts could change.

```
Error: No se puede crear una entrada de diario no balanceada.. Ids: [209]

Diferencias débito - crédito: [0.08]
```

Now was fixed

Copies from:
https://git.vauxoo.com/vauxoo/vendor-bills/-/commit/e80fb05f57ae53b9b92a35175f539602aa76907a